[package]
name = "my_rust_eval"
version = "1.0.0"
authors = ["Bobink <bobink@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
